---
- hosts: localhost
  tasks:
    - name: Download warfile
      command: curl -O https://github.com/manjuyadrami/dockerwithwar/blob/master/java-tomcat-maven-example.war
    - name: Copy the artifact to deployment directory
      shell: cp /Users/sarvam/.jenkins/workspace/ansible-deploy/java-tomcat-maven-example.war /Users/sarvam/Downloads/apache-tomcat-10.1.17/webapps
    - name: Start tomcat
      shell: /Users/sarvam/Downloads/apache-tomcat-10.1.17/bin/startup.sh
